# Generated by Django 5.1.2 on 2024-11-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filename',
        ),
    ]
