# Generated by Django 5.1.2 on 2024-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_upload_date_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='default_filename.txt', max_length=255),
        ),
    ]
