# Generated by Django 5.1.2 on 2024-11-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_uploadedfile_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
