# Generated by Django 5.1.2 on 2024-11-28 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_uploadedfile_file_alter_uploadedfile_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
