# Generated by Django 5.1.2 on 2024-11-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_uploadedfile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
