# Generated by Django 5.1.2 on 2024-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_uploadedfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='default_filename.txt', max_length=255),
            preserve_default=False,
        ),
    ]
