# Generated by Django 5.1.2 on 2024-11-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
