# Generated by Django 5.1.2 on 2024-12-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_deletedfile_delete_userfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
