# Generated by Django 5.1.2 on 2024-12-18 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_file_filename_file_uploaded_at_file_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.EmailField(max_length=254)),
                ('share_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permissions', models.CharField(choices=[('read', 'Read'), ('edit', 'Edit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='myapp.file')),
            ],
        ),
    ]
