# Generated by Django 5.1.2 on 2024-12-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_sharedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
