# Generated by Django 5.1.2 on 2024-12-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_owner_file_user_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='owner',
        ),
    ]
