# Generated by Django 5.1.2 on 2024-12-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_deletedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedfile',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='deletedfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='deletedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='deletedfile',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletedfile',
            name='deleted_at',
            field=models.DateTimeField(),
        ),
    ]
