# Generated by Django 5.1.2 on 2024-12-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_deletedfile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedfile',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
