# Generated by Django 5.1.2 on 2024-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_deletedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedfile',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
