# Generated by Django 5.1.2 on 2024-12-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_deletedfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
