# Generated by Django 5.1.2 on 2024-12-20 00:22

from django.db import migrations, models
import django.utils.timezone

def set_default_created_at(apps, schema_editor):
    File = apps.get_model('myapp', 'File')
    for file in File.objects.all():
        if not file.created_at:
            file.created_at = django.utils.timezone.now()
            file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_name_file_file_name_remove_file_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(set_default_created_at),
    ]
