# Generated by Django 5.1.2 on 2024-12-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_filename_uploadedfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
