# Generated by Django 5.1.2 on 2024-12-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_file_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
