# Generated by Django 5.1.2 on 2024-12-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
